### ISSUE TITLE
Undefined control sequence \pdfinfo

### ISSUE THREAD

**Issue by jilljenn** [profound-labs/prophecy-template#3]
Hi, if I just do `make`, I get an error about `\pdfinfo`. Is this a work in progress? Thanks.

**Comment by gambhiro** [comment]
Comment it out, it was removed in recent lualatex versions.

This is a book template I use with a few other people. It's a bit 'rough and ready'. We use it regularly but it usually needs a hands-on tutorial to see how the parts fit together.
